window.SMALL_GAMES = [
  {
    "id": 1,
    "slug": "grave-swarm",
    "folder": "01-grave-swarm",
    "title": "Grave Swarm",
    "version": "v0.21",
    "genre": "Survivors-like \u00b7 Army Growth",
    "hook": "Every enemy you kill rises and joins your undead army.",
    "accent": "#9b78ff",
    "symbol": "\u2620",
    "status": "DEMO"
  },
  {
    "id": 2,
    "slug": "starbore",
    "folder": "02-starbore",
    "title": "Starbore",
    "version": "v1.0",
    "genre": "Space Mining \u00b7 Progression",
    "hook": "Mine strange planets, chase jackpots, and upgrade your rig and ship.",
    "accent": "#63d7f0",
    "symbol": "\u2726",
    "status": "DEMO"
  },
  {
    "id": 3,
    "slug": "patchwork",
    "folder": "03-patchwork",
    "title": "Project Patchwork",
    "version": "v9",
    "genre": "Auto-battler \u00b7 Buildcraft",
    "hook": "Stitch bizarre body parts into a monster and watch the build fight.",
    "accent": "#ff8fc6",
    "symbol": "\u271a",
    "status": "DEMO"
  },
  {
    "id": 4,
    "slug": "mimic",
    "folder": "04-mimic",
    "title": "Project Mimic",
    "version": "v0.7",
    "genre": "Push Your Luck \u00b7 Deduction",
    "hook": "Open one more chest, manipulate the odds, or bank before it bites.",
    "accent": "#ffca59",
    "symbol": "\u25c8",
    "status": "DEMO"
  },
  {
    "id": 5,
    "slug": "dungeon-drop",
    "folder": "05-dungeon-drop",
    "title": "Dungeon Drop",
    "version": "v1.2",
    "genre": "Physics Roguelike \u00b7 Combos",
    "hook": "Build the dungeon, then bounce adventurers through your traps.",
    "accent": "#f28d52",
    "symbol": "\u25bc",
    "status": "DEMO"
  },
  {
    "id": 6,
    "slug": "wildcards",
    "folder": "06-wildcards",
    "title": "Project Wildcards",
    "version": "v008",
    "genre": "Ecosystem \u00b7 Management",
    "hook": "Build a living ecosystem and stop it from eating itself.",
    "accent": "#77df91",
    "symbol": "\u274b",
    "status": "DEMO"
  },
  {
    "id": 7,
    "slug": "scrap-run",
    "folder": "07-scrap-run",
    "title": "Scrap Run",
    "version": "v3",
    "genre": "Arcade \u00b7 Extraction",
    "hook": "Go deeper for better salvage, then survive the same route home.",
    "accent": "#f1ba4e",
    "symbol": "\u2b22",
    "status": "DEMO"
  },
  {
    "id": 8,
    "slug": "last-line",
    "folder": "08-last-line",
    "title": "Last Line",
    "version": "v0.3",
    "genre": "Transit \u00b7 Evacuation",
    "hook": "Keep the network moving while a disaster consumes the city.",
    "accent": "#55d8ff",
    "symbol": "\u2301",
    "status": "DEMO"
  },
  {
    "id": 9,
    "slug": "grid-siege",
    "folder": "09-grid-siege",
    "title": "Grid Siege",
    "version": "v2",
    "genre": "Block Puzzle \u00b7 Defense",
    "hook": "Rows fire east and west. Columns fire north and south.",
    "accent": "#ef7777",
    "symbol": "\u25a6",
    "status": "PROTOTYPE"
  },
  {
    "id": 10,
    "slug": "dead-orbit",
    "folder": "10-dead-orbit",
    "title": "Dead Orbit",
    "version": "v8",
    "genre": "Engine Builder \u00b7 Survival",
    "hook": "Build a dying spaceship into an impossible machine before the crew runs out of air.",
    "accent": "#70eaff",
    "symbol": "\u25ce",
    "status": "PROTOTYPE"
  },
  {
    "id": 11,
    "slug": "cauldron",
    "folder": "11-cauldron",
    "title": "Project Cauldron",
    "version": "v7",
    "genre": "Physics Merge \u00b7 Shop Strategy",
    "hook": "Merge ingredients into bigger tiers, but customers want exact ingredients—bottle them now or gamble by merging higher.",
    "accent": "#b68cff",
    "symbol": "\u2697",
    "status": "PROTOTYPE"
  },
  {
    "id": 12,
    "slug": "gatekeeper",
    "folder": "12-gatekeeper",
    "title": "Project Gatekeeper",
    "version": "v7",
    "genre": "Inspection \u00b7 Party Strategy",
    "hook": "Inspect fantasy adventurers, then decide whether their paperwork—and their party—can survive the dungeon.",
    "accent": "#e7bd6c",
    "symbol": "\u2696",
    "status": "PROTOTYPE"
  },
  {
    "id": 13,
    "slug": "ringkeep",
    "folder": "13-ringkeep",
    "title": "Ringkeep",
    "version": "v11",
    "genre": "Streamlined Kingdom Builder \u00b7 Active Tower Defense",
    "hook": "Build a kingdom on three rotating fortress rings. Rotating a ring moves every attached building, letting you reposition defenses while potentially exposing your economy.",
    "accent": "#d7a650",
    "symbol": "\u25ce",
    "status": "PLAYTEST READY"
  },
  {
    "id": 14,
    "slug": "devourer",
    "folder": "14-devourer",
    "title": "Project Devourer",
    "version": "v4",
    "genre": "Incremental \u00b7 Buildcraft",
    "hook": "Grow a lab creature whose organs are the upgrade tree—rearrange mutations, molt, and break containment.",
    "accent": "#81de72",
    "symbol": "\u2623",
    "status": "PROTOTYPE"
  }
];
