window.SMALL_GAMES = [
  {
    "id": 1,
    "slug": "grave-swarm",
    "folder": "01-grave-swarm",
    "title": "Grave Swarm",
    "version": "v0.21",
    "genre": "Survivors-like · Army Growth",
    "hook": "Every enemy you kill rises and joins your undead army.",
    "accent": "#9b78ff",
    "symbol": "☠",
    "status": "DEMO"
  },
  {
    "id": 2,
    "slug": "starbore",
    "folder": "02-starbore",
    "title": "Starbore",
    "version": "v1.0",
    "genre": "Space Mining · Progression",
    "hook": "Mine strange planets, chase jackpots, and upgrade your rig and ship.",
    "accent": "#63d7f0",
    "symbol": "✦",
    "status": "DEMO"
  },
  {
    "id": 3,
    "slug": "patchwork",
    "folder": "03-patchwork",
    "title": "Project Patchwork",
    "version": "v9",
    "genre": "Auto-battler · Buildcraft",
    "hook": "Stitch bizarre body parts into a monster and watch the build fight.",
    "accent": "#ff8fc6",
    "symbol": "✚",
    "status": "DEMO"
  },
  {
    "id": 4,
    "slug": "mimic",
    "folder": "04-mimic",
    "title": "Project Mimic",
    "version": "v0.7",
    "genre": "Push Your Luck · Deduction",
    "hook": "Open one more chest, manipulate the odds, or bank before it bites.",
    "accent": "#ffca59",
    "symbol": "◈",
    "status": "DEMO"
  },
  {
    "id": 5,
    "slug": "dungeon-drop",
    "folder": "05-dungeon-drop",
    "title": "Dungeon Drop",
    "version": "v1.2",
    "genre": "Physics Roguelike · Combos",
    "hook": "Build the dungeon, then bounce adventurers through your traps.",
    "accent": "#f28d52",
    "symbol": "▼",
    "status": "DEMO"
  },
  {
    "id": 6,
    "slug": "wildcards",
    "folder": "06-wildcards",
    "title": "Project Wildcards",
    "version": "v008",
    "genre": "Ecosystem · Management",
    "hook": "Build a living ecosystem and stop it from eating itself.",
    "accent": "#77df91",
    "symbol": "❋",
    "status": "DEMO"
  },
  {
    "id": 7,
    "slug": "scrap-run",
    "folder": "07-scrap-run",
    "title": "Scrap Run",
    "version": "v3",
    "genre": "Arcade · Extraction",
    "hook": "Go deeper for better salvage, then survive the same route home.",
    "accent": "#f1ba4e",
    "symbol": "⬢",
    "status": "DEMO"
  },
  {
    "id": 8,
    "slug": "last-line",
    "folder": "08-last-line",
    "title": "Last Line",
    "version": "v0.3",
    "genre": "Transit · Evacuation",
    "hook": "Keep the network moving while a disaster consumes the city.",
    "accent": "#55d8ff",
    "symbol": "⌁",
    "status": "DEMO"
  },
  {
    "id": 9,
    "slug": "grid-siege",
    "folder": "09-grid-siege",
    "title": "Grid Siege",
    "version": "v2",
    "genre": "Block Puzzle · Defense",
    "hook": "Rows fire east and west. Columns fire north and south.",
    "accent": "#ef7777",
    "symbol": "▦",
    "status": "PROTOTYPE"
  },
  {
    "id": 10,
    "slug": "dead-orbit",
    "folder": "10-dead-orbit",
    "title": "Dead Orbit",
    "version": "v8",
    "genre": "Engine Builder · Survival",
    "hook": "Build a dying spaceship into an impossible machine before the crew runs out of air.",
    "accent": "#70eaff",
    "symbol": "◎",
    "status": "PROTOTYPE"
  },
  {
    "id": 11,
    "slug": "cauldron",
    "folder": "11-cauldron",
    "title": "Project Cauldron",
    "version": "v7",
    "genre": "Physics Merge · Shop Strategy",
    "hook": "Merge ingredients into bigger tiers, but customers want exact ingredients—bottle them now or gamble by merging higher.",
    "accent": "#b68cff",
    "symbol": "⚗",
    "status": "PROTOTYPE"
  },
  {
    "id": 12,
    "slug": "gatekeeper",
    "folder": "12-gatekeeper",
    "title": "Project Gatekeeper",
    "version": "v7",
    "genre": "Inspection · Party Strategy",
    "hook": "Inspect fantasy adventurers, then decide whether their paperwork—and their party—can survive the dungeon.",
    "accent": "#e7bd6c",
    "symbol": "⚖",
    "status": "PROTOTYPE"
  },
  {
    "id": 13,
    "slug": "ringkeep",
    "folder": "13-ringkeep",
    "title": "Ringkeep",
    "version": "v11",
    "genre": "Streamlined Kingdom Builder · Active Tower Defense",
    "hook": "Build a kingdom on three rotating fortress rings. Rotating a ring moves every attached building, letting you reposition defenses while potentially exposing your economy.",
    "accent": "#d7a650",
    "symbol": "◎",
    "status": "PLAYTEST READY"
  },
  {
    "id": 14,
    "slug": "devourer",
    "folder": "14-devourer",
    "title": "Project Devourer",
    "version": "v4",
    "genre": "Incremental · Buildcraft",
    "hook": "Grow a lab creature whose organs are the upgrade tree—rearrange mutations, molt, and break containment.",
    "accent": "#81de72",
    "symbol": "☣",
    "status": "PROTOTYPE"
  },
  {
    "id": 15,
    "slug": "scrapdice",
    "folder": "15-scrapdice",
    "title": "Project Scrapdice",
    "version": "v10",
    "genre": "Dice Roguelike · Squad Buildcraft",
    "hook": "Build each robot’s die, read enemy intents, and sequence the roll to survive the scrapyard.",
    "accent": "#ffd45a",
    "symbol": "⚄",
    "status": "PROTOTYPE"
  },
  {
    "id": 16,
    "slug": "crown-eater",
    "folder": "16-crown-eater",
    "title": "Project Crown Eater",
    "version": "v6",
    "genre": "Tactical Roguelike · Movement Buildcraft",
    "hook": "Devour court pieces to steal their movement, then redirect the board against itself.",
    "accent": "#f3c75d",
    "symbol": "♛",
    "status": "PROTOTYPE"
  },
  {
    "id": 17,
    "slug": "polarity",
    "folder": "17-polarity",
    "title": "Project Polarity",
    "version": "v1",
    "genre": "Arena Roguelite · Bullet Capture",
    "hook": "Catch the bullet hell in a magnetic orbit, then fire the enemy’s ammunition back.",
    "accent": "#63e9ff",
    "symbol": "∩",
    "status": "PROTOTYPE"
  },
  {
    "id": 18,
    "slug": "flux-foundry",
    "folder": "18-flux-foundry",
    "title": "Flux Foundry",
    "version": "v4",
    "genre": "Automation Puzzle · Factory",
    "hook": "Build a tiny factory that must keep producing after reality flips.",
    "accent": "#9b78ff",
    "symbol": "⇄",
    "status": "PROTOTYPE"
  },
  {
    "id": 19,
    "slug": "server-of-one",
    "folder": "19-server-of-one",
    "title": "Project Server of One",
    "version": "v7",
    "genre": "Single-Player MMORPG · Server Simulation",
    "hook": "Play one adventurer in an MMORPG where every other player, party, guild, economy, and server story is simulated.",
    "accent": "#e8c66a",
    "symbol": "◉",
    "status": "PROTOTYPE"
  },
  {
    "id": 20,
    "slug": "fire-crew",
    "folder": "20-fire-crew",
    "title": "Fire Crew",
    "version": "v4",
    "genre": "Arcade Rescue · Vehicle Action",
    "hook": "Race to emergencies, extinguish escalating fires, rescue civilians, and upgrade your fire truck.",
    "accent": "#ff6a43",
    "symbol": "🔥",
    "status": "POKI CANDIDATE"
  }
];
