import fsp from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';

export const ASSET_LIBRARY_VERSION='1.0.0';
const SAFE_EXT=new Set(['.svg','.png','.webp','.jpg','.jpeg','.json','.glb','.gltf','.mp3','.wav','.ogg']);
const SKIP_NAMES=new Set(['asset-catalog.json','asset-autopilot.json','library-matches.json']);

function rootFor(stateDir){return path.join(stateDir,'asset-library')}
function catalogFile(stateDir){return path.join(rootFor(stateDir),'catalog.json')}
function clean(value='asset'){return String(value||'asset').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,72)||'asset'}
function words(value=''){return[...new Set(String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>=2))]}
async function readJson(file,fallback){try{return JSON.parse(await fsp.readFile(file,'utf8'))}catch{return fallback}}
async function exists(file){return Boolean((await fsp.stat(file).catch(()=>null))?.isFile())}
async function ensure(stateDir){const root=rootFor(stateDir);await fsp.mkdir(path.join(root,'files'),{recursive:true});const file=catalogFile(stateDir);if(!await exists(file))await fsp.writeFile(file,JSON.stringify({version:ASSET_LIBRARY_VERSION,assets:[],updatedAt:new Date().toISOString()},null,2),'utf8');return root}
async function saveCatalog(stateDir,catalog){await ensure(stateDir);catalog.version=ASSET_LIBRARY_VERSION;catalog.updatedAt=new Date().toISOString();await fsp.writeFile(catalogFile(stateDir),JSON.stringify(catalog,null,2),'utf8')}
export async function getAssetLibrary({stateDir}){await ensure(stateDir);const data=await readJson(catalogFile(stateDir),{version:ASSET_LIBRARY_VERSION,assets:[]});return{version:ASSET_LIBRARY_VERSION,assets:Array.isArray(data.assets)?data.assets:[],updatedAt:data.updatedAt||null}}
async function hashFile(file){const b=await fsp.readFile(file);return{sha1:createHash('sha1').update(b).digest('hex'),bytes:b.length}}
async function walk(root,rel=''){let entries=[];try{entries=await fsp.readdir(path.join(root,rel),{withFileTypes:true})}catch{return[]};const out=[];for(const e of entries){const next=path.join(rel,e.name);if(e.isDirectory()){if(e.name==='library')continue;out.push(...await walk(root,next));continue}if(!e.isFile())continue;const ext=path.extname(e.name).toLowerCase();if(SAFE_EXT.has(ext)&&!SKIP_NAMES.has(e.name))out.push(next)}return out}
function localCatalogTags(localCatalog,rel){const normalized='./'+rel.replaceAll('\\','/');const found=(localCatalog.assets||[]).find(x=>x.source===normalized||x.vector===normalized||x.preview===normalized||String(x.source||'').endsWith('/'+path.basename(rel))||String(x.vector||'').endsWith('/'+path.basename(rel)));return found?[found.name,found.mode,found.mime,found.id].filter(Boolean).flatMap(words):[]}
function inferTags({rel,metadata={},localCatalog={}}){return[...new Set([...words(rel),...words(metadata.title),...words(metadata.concept),...words(metadata.artStyle),...words(metadata.opportunity),...localCatalogTags(localCatalog,rel)])].slice(0,48)}
function scoreEntry(entry,queryTokens){if(!queryTokens.length)return Math.min(18,Number(entry.uses||0)*2);const hay=new Set([...words(entry.name),...(entry.tags||[]).flatMap(words),...words(entry.sourceGame),...words(entry.kind)]);let score=0;for(const token of queryTokens){if(hay.has(token))score+=12;else for(const h of hay)if(h.includes(token)||token.includes(h)){score+=4;break}}score+=Math.min(12,Number(entry.uses||0)*1.5);return score}
export async function searchAssetLibrary({stateDir,query='',limit=12}){const catalog=await getAssetLibrary({stateDir}),tokens=words(query),results=catalog.assets.map(asset=>({...asset,matchScore:scoreEntry(asset,tokens)})).filter(x=>x.matchScore>0).sort((a,b)=>b.matchScore-a.matchScore||Number(b.uses||0)-Number(a.uses||0)).slice(0,Math.max(1,Math.min(40,Number(limit)||12)));return{version:ASSET_LIBRARY_VERSION,query,results,total:catalog.assets.length}}

export async function harvestGameAssets({stateDir,gameDir,game='',metadata={}}){await ensure(stateDir);const assetsRoot=path.join(gameDir,'assets'),rels=await walk(assetsRoot),catalog=await getAssetLibrary({stateDir}),localCatalog=await readJson(path.join(assetsRoot,'asset-catalog.json'),{assets:[]});let added=0,reused=0;for(const rel0 of rels){const rel=rel0.replaceAll('\\','/');if(rel.startsWith('library/'))continue;const source=path.join(assetsRoot,rel0),finger=await hashFile(source).catch(()=>null);if(!finger)continue;let entry=catalog.assets.find(x=>x.sha1===finger.sha1);if(entry){entry.lastSeenAt=new Date().toISOString();entry.sourceGames=[...new Set([...(entry.sourceGames||[]),game].filter(Boolean))];entry.tags=[...new Set([...(entry.tags||[]),...inferTags({rel,metadata,localCatalog})])].slice(0,64);reused++;continue}const stem=clean(path.basename(rel,path.extname(rel))),id=(stem+'-'+finger.sha1.slice(0,10)).slice(0,86),dir=path.join(rootFor(stateDir),'files',id);await fsp.mkdir(dir,{recursive:true});const dest=path.join(dir,path.basename(rel));await fsp.copyFile(source,dest);entry={id,name:stem,kind:path.extname(rel).slice(1).toLowerCase()||'file',sha1:finger.sha1,bytes:finger.bytes,file:path.relative(rootFor(stateDir),dest).replaceAll('\\','/'),tags:inferTags({rel,metadata,localCatalog}),sourceGame:game||null,sourceGames:game?[game]:[],sourcePath:'assets/'+rel,uses:0,createdAt:new Date().toISOString(),lastSeenAt:new Date().toISOString()};catalog.assets.push(entry);added++}await saveCatalog(stateDir,catalog);return{version:ASSET_LIBRARY_VERSION,added,reused,total:catalog.assets.length}}

async function mergeLocalCatalog(gameDir,entries){const file=path.join(gameDir,'assets','asset-catalog.json'),current=await readJson(file,{version:'library',assets:[]});current.assets=Array.isArray(current.assets)?current.assets:[];for(const e of entries){const item={id:'library-'+e.id,name:e.name,mode:'global-library',mime:e.kind,bytes:e.bytes,source:e.installedSource,vector:e.kind==='json'?e.installedSource:null,preview:e.kind==='svg'?e.installedSource:null,createdAt:new Date().toISOString(),libraryAssetId:e.id,usage:e.kind==='svg'?`Use as SVG/vector art or import/extrude where appropriate: ${e.installedSource}`:`Reuse installed library asset: ${e.installedSource}`};if(!current.assets.some(x=>x.libraryAssetId===e.id))current.assets.push(item)}current.updatedAt=new Date().toISOString();await fsp.mkdir(path.dirname(file),{recursive:true});await fsp.writeFile(file,JSON.stringify(current,null,2),'utf8')}

export async function installLibraryMatches({stateDir,gameDir,query='',limit=10}){const found=await searchAssetLibrary({stateDir,query,limit}),root=rootFor(stateDir),installed=[];for(const asset of found.results){const src=path.join(root,asset.file||'');if(!await exists(src))continue;const dir=path.join(gameDir,'assets','library',asset.id);await fsp.mkdir(dir,{recursive:true});const dest=path.join(dir,path.basename(src));await fsp.copyFile(src,dest);asset.uses=Number(asset.uses||0)+1;asset.lastUsedAt=new Date().toISOString();installed.push({...asset,installedSource:'./'+path.relative(gameDir,dest).replaceAll('\\','/')})}if(installed.length){const catalog=await getAssetLibrary({stateDir});for(const hit of installed){const target=catalog.assets.find(x=>x.id===hit.id);if(target){target.uses=hit.uses;target.lastUsedAt=hit.lastUsedAt}}await saveCatalog(stateDir,catalog);await mergeLocalCatalog(gameDir,installed)}const manifest={version:ASSET_LIBRARY_VERSION,query,installed:installed.map(({matchScore,...x})=>x),generatedAt:new Date().toISOString()};await fsp.mkdir(path.join(gameDir,'assets','library'),{recursive:true});await fsp.writeFile(path.join(gameDir,'assets','library','library-matches.json'),JSON.stringify(manifest,null,2),'utf8');return manifest}

export async function assetLibraryStats({stateDir}){const lib=await getAssetLibrary({stateDir});const kinds={};let bytes=0;for(const a of lib.assets){kinds[a.kind]=(kinds[a.kind]||0)+1;bytes+=Number(a.bytes||0)}return{version:ASSET_LIBRARY_VERSION,total:lib.assets.length,bytes,kinds,updatedAt:lib.updatedAt}}
