import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { runQa } from './qa.js';
import { runPokiReadiness } from './poki-readiness.js';
import { runAiPlaytest } from './playtester.js';
import { runRetentionAudit } from './retention.js';
import { runAdReadiness } from './ad-readiness.js';
import { parseVisualRubric, visualRubricAuditInstructions } from './visual-quality.js';

const CODEX_COMMAND=process.env.GAME_FACTORY_CODEX_COMMAND||'codex';
function runProcess(command,args,{cwd,input='',timeoutMs=8*60*1000}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{cwd,env:process.env,windowsHide:true,shell:process.platform==='win32'});let stdout='',stderr='',settled=false;child.stdout?.on('data',chunk=>{stdout+=chunk.toString();if(stdout.length>140000)stdout=stdout.slice(-140000)});child.stderr?.on('data',chunk=>{stderr+=chunk.toString();if(stderr.length>120000)stderr=stderr.slice(-120000)});const timer=setTimeout(()=>{if(settled)return;settled=true;child.kill();reject(new Error(`Quality review timed out after ${Math.round(timeoutMs/60000)} minutes`))},timeoutMs);child.on('error',error=>{if(settled)return;settled=true;clearTimeout(timer);reject(error)});child.on('close',code=>{if(settled)return;settled=true;clearTimeout(timer);resolve({code,stdout,stderr})});if(child.stdin){child.stdin.write(input);child.stdin.end()}})}
function extractScore(text=''){const match=text.match(/(?:overall(?:\s+quality)?\s+score|quality\s+score)\s*[:*-]*\s*(\d{1,3})\s*\/\s*100/i)||text.match(/\b(\d{1,3})\s*\/\s*100\b/);return match?Math.max(0,Math.min(100,Number(match[1]))):null}
function formatBytes(bytes=0){return bytes<1024*1024?`${Math.round(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`}
function playtestSummary(playtest){const sessions=playtest.sessions||[],lines=[`AI playtest score: ${playtest.score}/100`,`Planner confidence: ${playtest.plan?.confidence||'unknown'}`,`Inferred objective: ${playtest.plan?.objective||'unknown'}`,`Plan: ${playtest.plan?.summary||'unknown'}`];for(const device of['desktop','phone']){const runs=sessions.filter(run=>run.device===device),visualChanges=runs.reduce((sum,run)=>sum+run.visualChanges,0),activeActions=runs.reduce((sum,run)=>sum+run.activeActionCount,0),terminal=runs.filter(run=>run.terminal).map(run=>`${run.terminal.type}:${run.terminal.term}`).join(', ')||'not reached',errors=runs.reduce((sum,run)=>sum+run.errors.length,0);lines.push(`${device}: ${runs.length} runs; visual response ${visualChanges}/${activeActions} active actions; terminal=${terminal}; errors=${errors}`)}lines.push(`Findings: ${(playtest.notes||[]).join(' | ')||'none'}`);return lines.join('\n')}
function retentionSummary(r){return[`Retention/replay score: ${r.score}/100`,`Replay route: ${r.restartAvailable?`verified (${r.restartControl||'restart'})`:r.secondRunStarted?'second run can start':'not verified'}`,`Meaningful upgrade effect: ${r.meaningfulUpgradeVerified?'verified':r.source?.upgrades?'not verified':'n/a'}`,`Second-run differentiation: ${r.secondRunMeaningfullyDifferent?'verified':'not verified'}`,`Persistence: ${r.persistedAfterReload?'verified':r.source?.persistence?'present/not demonstrated':'not detected'}`,`Replay systems: upgrades=${Boolean(r.source?.upgrades)}, score=${Boolean(r.source?.scoreChase)}, missions=${Boolean(r.source?.missions)}, progression=${Boolean(r.source?.progression)}, variation=${Boolean(r.source?.variation)}`,`Findings: ${(r.notes||[]).join(' | ')||'none'}`].join('\n')}
function adSummary(ad){if(!ad?.applicable)return'Ad readiness: not applicable for this target.';return[`Ad readiness score: ${ad.score}/100`,`commercialBreak: ${ad.source?.commercial?'yes':'no'}; natural moment=${ad.source?.naturalCommercialContext||ad.runtime?.commercialRuntime?'verified':'not verified'}`,`rewardedBreak: ${ad.source?.rewarded?'yes':'no'}; explicit choice=${ad.source?.explicitRewardChoice||ad.runtime?.rewardedButton?'verified':'not verified'}`,`Reward success guarded: ${ad.source?.rewardSuccessGuard?'yes':'no'}`,`No ad before player intent: ${ad.runtime?.noAdBeforeInput?'PASS':'FAIL'}`,`Ad pause hooks: ${ad.source?.adPauseHooks?'detected':'not detected'}`,`Findings: ${(ad.notes||[]).join(' | ')||'none'}`].join('\n')}
async function progress(onProgress,percent,stage,detail){if(typeof onProgress==='function')await onProgress({percent,stage,detail,at:new Date().toISOString()})}

async function runVisualDirector({gameDir,artifactDir,qa,playtest,readiness,retention,adReadiness}){
  const images=['desktop.png','mobile.png','playtest-desktop.png','playtest-phone.png'].map(name=>path.join(artifactDir,name)),existing=[];for(const image of images){try{await fsp.access(image);existing.push(image)}catch{}}if(!existing.length)return{report:'Visual Director could not run because no screenshots were produced.',score:null,rubric:null,error:'No screenshots'};
  const technicalSummary=qa.views.map(view=>`${view.name}: ${view.passed?'PASS':'FAIL'}; ${view.issues.join(' | ')||'no technical issues'}`).join('\n');
  const performanceSummary=[`Performance score: ${readiness.performanceScore}/100`,`Poki readiness score: ${readiness.pokiScore}/100`,`Meaningful UI: ${readiness.metrics.meaningfulReadyMs??'unknown'} ms local`,`Initial payload: ${formatBytes(readiness.metrics.initialBytes)}`,`Requests: ${readiness.metrics.initialRequests}`,`4 Mbps estimate: ${readiness.metrics.estimated4MbpsReadyMs} ms`,`FPS: ${readiness.metrics.frame.fps||'unknown'}; long frames ${Math.round((readiness.metrics.frame.longFrameRatio||0)*100)}%`,`Ad-block resilience: ${readiness.adBlock.passed?'PASS':'FAIL'}`,`SDK event sequence: ${readiness.sdkEvents?.passed?'PASS':'FAIL'}`,`Findings: ${readiness.performanceNotes.join(' | ')} | ${readiness.pokiNotes.join(' | ')}`].join('\n');
  const prompt=`model: terra\nYou are the senior VISUAL DIRECTOR and GAME DOCTOR inside Gutpopper Game Factory.\n\nREAD-ONLY audit. Do not modify files. Attached: desktop QA 1440x900, phone QA 390x844, AI Playtester desktop, AI Playtester phone when available.\n\nTECHNICAL QA\n${technicalSummary}\n\nAI PLAYTESTER\n${playtestSummary(playtest)}\n\nRETENTION / REPLAY\n${retentionSummary(retention)}\n\nAD READINESS\n${adSummary(adReadiness)}\n\nPOKI / WEB PERFORMANCE\n${performanceSummary}\n\nJudge this against strong modern Poki/mobile-casual games, not coding prototypes. Be particularly severe about flat/depthless scenes, weak/no lighting and shadows, muddy color, single-primitive vehicles/characters/props, empty worlds, generic dashboard UI, stiff/linear animation, missing secondary motion, weak particles/trails/camera response, and lack of professional success/failure celebration. Bright color without depth and motion is not enough.\n\nDesktop must be intentionally landscape. Phone must be touch-first. Retention can come from progression OR score chase/variation/mastery. Rewarded ads must remain optional and clearly disclosed. Protect performance.\n\n${visualRubricAuditInstructions()}\n\nReturn concise markdown using EXACTLY these headings before the required VISUAL_RUBRIC_JSON block:\nOVERALL QUALITY SCORE: NN/100\n## What Works\n## Visual Problems\n## Phone Problems\n## Gameplay / Feel Concerns\n## Retention / Replay Concerns\n## Ads / Monetization Concerns\n## Performance / Poki Concerns\n## Top 5 Fixes\n## Publish Verdict\nBe severe about amateur-looking presentation and make fixes implementation-ready.`;
  const args=['exec','--ephemeral','--sandbox','read-only','-c','approval_policy=never','-m','gpt-5.6-terra','-c','model_reasoning_effort=medium','-c','model_verbosity=low','--color','never'];for(const image of existing)args.push('--image',image);args.push('-C',gameDir,'-');
  try{const result=await runProcess(CODEX_COMMAND,args,{cwd:gameDir,input:prompt});if(result.code!==0){const detail=(result.stderr||result.stdout||'').trim().slice(-3000);throw new Error(`Codex visual review exited with code ${result.code}${detail?`: ${detail}`:''}`)}const report=result.stdout.trim()||'Visual Director returned no report text.',rubric=parseVisualRubric(report),score=rubric?.score??extractScore(report);return{report,score,rubric,error:rubric?null:'Visual rubric block missing/invalid; using report score.'}}catch(error){return{report:`Visual Director unavailable: ${error.message}`,score:null,rubric:null,error:error.message}}
}

export async function runQualityAudit({game,gameDir,url,stateDir,onProgress=null}){
  const id=`${new Date().toISOString().replace(/[:.]/g,'-')}-${randomUUID().slice(0,8)}`,artifactDir=path.join(stateDir,'quality',id);await fsp.mkdir(artifactDir,{recursive:true});const startedAt=new Date().toISOString();
  await progress(onProgress,3,'Starting Game Doctor','Preparing isolated audit workspace and reading the selected game.');
  await progress(onProgress,8,'Performance + Poki readiness','Measuring cold start, local payload, requests, frame pacing, SDK lifecycle and ad-block resilience.');
  const readiness=await runPokiReadiness({gameDir,url});
  await progress(onProgress,23,'Desktop + phone QA','Opening the game at 1440×900 and 390×844, checking runtime errors, overflow, layout and screenshots.');
  const qa=await runQa({url,artifactDir});
  await progress(onProgress,40,'AI Playtester','Inferring the controls/objective and running fresh desktop and phone play sessions.');
  const playtest=await runAiPlaytest({gameDir,url,artifactDir});
  await progress(onProgress,64,'Retention + ad readiness','Testing replay, progression, persistence, meaningful upgrades and optional Poki ad opportunities.');
  const[retention,adReadiness]=await Promise.all([runRetentionAudit({gameDir,url,playtestPlan:playtest.plan}),runAdReadiness({gameDir,url,playtestPlan:playtest.plan})]);
  if(adReadiness.applicable)readiness.pokiNotes=[...(readiness.pokiNotes||[]),`Ad readiness: ${adReadiness.score}/100 (${adReadiness.passed?'PASS':'NEEDS WORK'})`,...(adReadiness.notes||[]).map(note=>`Ads: ${note}`)];
  await progress(onProgress,82,'Visual Director','Reviewing QA/playtest screenshots against the professional visual-quality rubric.');
  const visual=await runVisualDirector({gameDir,artifactDir,qa,playtest,readiness,retention,adReadiness});
  await progress(onProgress,96,'Scoring + report','Combining technical, playtest, retention, performance, Poki and visual evidence.');
  const technicalScore=qa.passed?100:Math.max(30,100-qa.issues.length*12),playtestScore=playtest.score,visualScore=visual.score??Math.round((technicalScore+playtestScore)/2),retentionScore=retention.score,adScore=adReadiness.applicable?adReadiness.score:100;
  const overallScore=Math.round(visualScore*.38+technicalScore*.05+playtestScore*.13+retentionScore*.14+readiness.performanceScore*.12+readiness.pokiScore*.08+adScore*.10);
  const visualFloor=visual.rubric||{version:null,score:visualScore,status:visualScore>=78?'PASS':visualScore>=60?'NEEDS_POLISH':'VISUAL_FAIL',passed:visualScore>=78,minimumPrototypeScore:78,publishCandidateScore:85,categories:{},hardFails:[],summary:'Visual rubric details were unavailable.'};
  const audit={id,game,startedAt,finishedAt:new Date().toISOString(),overallScore,technicalScore,interactionScore:playtestScore,playtestScore,retentionScore,retentionPassed:retention.passed,adScore:adReadiness.applicable?adReadiness.score:null,adPassed:adReadiness.passed,visualScore,visualFloor,visualFloorPassed:visualFloor.passed,performanceScore:readiness.performanceScore,pokiScore:readiness.pokiScore,qa,playtest,retention,adReadiness,readiness,visualReport:visual.report,visualError:visual.error,artifacts:{desktop:'desktop.png',phone:'mobile.png',desktopPlay:'playtest-desktop.png',phonePlay:'playtest-phone.png'}};
  await fsp.writeFile(path.join(artifactDir,'audit.json'),JSON.stringify(audit,null,2),'utf8');
  await progress(onProgress,100,'Game Doctor complete',`Overall ${overallScore}/100 · visual ${visualScore}/100 · performance ${readiness.performanceScore}/100.`);
  return audit;
}
