import { getStudioPlan, saveStudioPlan, runHookAudit, thumbnailDirections, runOptimizationAudit, detectGodot, advancedAssetStatus, portfolioRank, STUDIO_TOOLS_VERSION } from './studio-tools.js';
import { getTestFunnel } from './test-funnel.js';
import { buildPlanPreview } from './plan-preview.js';
import { prepareAssetAutopilot, getAssetAutopilotStatus, linkAssetAutopilotJob, finishAssetAutopilot, assetAutopilotLibraryView, ASSET_AUTOPILOT_VERSION } from './asset-autopilot.js';
import { harvestGameAssets, assetLibraryStats } from './asset-library.js';

function safe(value){return typeof value==='string'&&/^[a-zA-Z0-9._-]+$/.test(value)&&!value.includes('..')}

export async function handleStudioApi({req,res,url,stateDir,store,gameInfo,listGames,readBody,sendJson}){
  if(req.method==='POST'&&url.pathname==='/api/new-game-plan'){try{return sendJson(res,200,buildPlanPreview(await readBody(req,500000)))}catch(error){return sendJson(res,400,{error:error.message})}}
  if(req.method==='GET'&&url.pathname==='/api/toolchain-status')return sendJson(res,200,{version:STUDIO_TOOLS_VERSION,godot:detectGodot(),assets:advancedAssetStatus(),assetAutopilot:{version:ASSET_AUTOPILOT_VERSION,...await assetLibraryStats({stateDir})}});
  if(req.method==='GET'&&url.pathname==='/api/asset-library'){try{return sendJson(res,200,await assetAutopilotLibraryView({stateDir,query:url.searchParams.get('q')||'',limit:Number(url.searchParams.get('limit')||60)}))}catch(error){return sendJson(res,500,{error:`Asset Library failed: ${error.message}`})}}
  if(req.method==='GET'&&url.pathname==='/api/portfolio'){
    const games=await listGames(),jobs=await store.list(250),funnels={};
    for(const game of games){try{funnels[game.id]=await getTestFunnel({stateDir,game:game.id,title:game.title,concept:game.metadata?.concept||''})}catch{funnels[game.id]=null}}
    return sendJson(res,200,{version:STUDIO_TOOLS_VERSION,games:portfolioRank({games,jobs,funnels})});
  }
  const autopilot=url.pathname.match(/^\/api\/games\/([^/]+)\/asset-autopilot$/);if(autopilot){const game=decodeURIComponent(autopilot[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});if(req.method==='GET')return sendJson(res,200,await getAssetAutopilotStatus({gameDir:info.gameDir}));if(req.method==='POST'){try{return sendJson(res,200,await prepareAssetAutopilot({stateDir,gameDir:info.gameDir,game,metadata:{id:game,title:info.title,...info.metadata}}))}catch(error){return sendJson(res,400,{error:`Asset Autopilot prepare failed: ${error.message}`})}}}
  const autopilotJob=url.pathname.match(/^\/api\/games\/([^/]+)\/asset-autopilot\/job$/);if(req.method==='POST'&&autopilotJob){const game=decodeURIComponent(autopilotJob[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});try{const body=await readBody(req,100000),jobId=String(body.jobId||'');if(!jobId)return sendJson(res,400,{error:'jobId is required'});const job=await store.get(jobId);if(!job||job.game!==game)return sendJson(res,404,{error:'Asset Autopilot job not found for this game'});return sendJson(res,200,await linkAssetAutopilotJob({gameDir:info.gameDir,jobId}))}catch(error){return sendJson(res,400,{error:error.message})}}
  const autopilotFinish=url.pathname.match(/^\/api\/games\/([^/]+)\/asset-autopilot\/finish$/);if(req.method==='POST'&&autopilotFinish){const game=decodeURIComponent(autopilotFinish[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});try{const body=await readBody(req,100000),jobId=String(body.jobId||''),job=jobId?await store.get(jobId):null;if(jobId&&!job)return sendJson(res,404,{error:'Asset Autopilot job not found'});if(job&&job.game!==game)return sendJson(res,400,{error:'Job belongs to another game'});return sendJson(res,200,await finishAssetAutopilot({stateDir,gameDir:info.gameDir,game,metadata:{id:game,title:info.title,...info.metadata},job}))}catch(error){return sendJson(res,400,{error:`Asset Autopilot finish failed: ${error.message}`})}}
  const harvest=url.pathname.match(/^\/api\/games\/([^/]+)\/asset-library\/harvest$/);if(req.method==='POST'&&harvest){const game=decodeURIComponent(harvest[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});try{return sendJson(res,200,await harvestGameAssets({stateDir,gameDir:info.gameDir,game,metadata:{id:game,title:info.title,...info.metadata}}))}catch(error){return sendJson(res,400,{error:`Asset harvest failed: ${error.message}`})}}
  const plan=url.pathname.match(/^\/api\/games\/([^/]+)\/studio-plan$/);if(plan){const game=decodeURIComponent(plan[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});if(req.method==='GET')return sendJson(res,200,await getStudioPlan({gameDir:info.gameDir,metadata:{id:game,title:info.title,...info.metadata}}));if(req.method==='POST'){try{return sendJson(res,200,await saveStudioPlan({gameDir:info.gameDir,metadata:{id:game,title:info.title,...info.metadata},input:await readBody(req,500000)}))}catch(error){return sendJson(res,400,{error:error.message})}}}
  const hook=url.pathname.match(/^\/api\/games\/([^/]+)\/hook-audit$/);if(req.method==='GET'&&hook){const game=decodeURIComponent(hook[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});return sendJson(res,200,await runHookAudit({gameDir:info.gameDir,metadata:{id:game,title:info.title,...info.metadata}}))}
  const thumb=url.pathname.match(/^\/api\/games\/([^/]+)\/thumbnail-lab$/);if(req.method==='GET'&&thumb){const game=decodeURIComponent(thumb[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});const planData=await getStudioPlan({gameDir:info.gameDir,metadata:{id:game,title:info.title,...info.metadata}});return sendJson(res,200,{version:STUDIO_TOOLS_VERSION,directions:thumbnailDirections({metadata:{id:game,title:info.title,...info.metadata},plan:planData})})}
  const opt=url.pathname.match(/^\/api\/games\/([^/]+)\/optimization$/);if(req.method==='GET'&&opt){const game=decodeURIComponent(opt[1]);if(!safe(game))return sendJson(res,400,{error:'Invalid game id'});const info=await gameInfo(game);if(!info)return sendJson(res,404,{error:'Game target not found'});return sendJson(res,200,await runOptimizationAudit({gameDir:info.gameDir}))}
  return false;
}
