import fsp from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';

export const STUDIO_TOOLS_VERSION='1.1.0';
const TEXT_EXT=new Set(['.html','.js','.mjs','.cjs','.css','.json','.svg','.txt','.md']);
const SKIP=new Set(['node_modules','.git','vendor']);
function clamp(v,a=0,b=100){return Math.max(a,Math.min(b,Math.round(Number(v)||0)))}
async function readJson(file,fallback){try{return JSON.parse(await fsp.readFile(file,'utf8'))}catch{return fallback}}
async function walk(root,rel=''){let entries=[];try{entries=await fsp.readdir(path.join(root,rel),{withFileTypes:true})}catch{return[]};const out=[];for(const e of entries){const r=path.join(rel,e.name);if(e.isDirectory()){if(!SKIP.has(e.name))out.push(...await walk(root,r))}else if(e.isFile())out.push(r)}return out}
async function textCorpus(gameDir){let text='';for(const rel of await walk(gameDir)){if(!TEXT_EXT.has(path.extname(rel).toLowerCase()))continue;try{const s=await fsp.readFile(path.join(gameDir,rel),'utf8');if(s.length<2_000_000)text+='\n'+s}catch{}}return text}
function planFile(gameDir){return path.join(gameDir,'studio-plan.json')}
export async function getStudioPlan({gameDir,metadata={}}){const fallback={version:STUDIO_TOOLS_VERSION,status:'draft',game:metadata.id||path.basename(gameDir),title:metadata.title||'',goal:'Prove the core hook with real players before expanding content.',hook:'',sessionZero:'',artDirection:'',assetPlan:'',monetization:'',testHypothesis:'',visualReferences:[],characterReferences:[],promptQueue:[],promptQueuePaused:false,approvedAt:null,updatedAt:null};const plan=await readJson(planFile(gameDir),fallback);return{...fallback,...plan,version:STUDIO_TOOLS_VERSION}}
export async function saveStudioPlan({gameDir,metadata={},input={}}){const current=await getStudioPlan({gameDir,metadata}),clean={...current,status:['draft','approved','building'].includes(input.status)?input.status:current.status,hook:String(input.hook??current.hook).slice(0,1800),sessionZero:String(input.sessionZero??current.sessionZero).slice(0,1800),artDirection:String(input.artDirection??current.artDirection).slice(0,2400),assetPlan:String(input.assetPlan??current.assetPlan).slice(0,2400),monetization:String(input.monetization??current.monetization).slice(0,1800),testHypothesis:String(input.testHypothesis??current.testHypothesis).slice(0,1800),visualReferences:Array.isArray(input.visualReferences)?input.visualReferences.slice(0,12).map(String):current.visualReferences,characterReferences:Array.isArray(input.characterReferences)?input.characterReferences.slice(0,4).map(String):current.characterReferences,promptQueuePaused:input.promptQueuePaused==null?Boolean(current.promptQueuePaused):Boolean(input.promptQueuePaused),promptQueue:Array.isArray(input.promptQueue)?input.promptQueue.slice(0,30).map((x,i)=>({id:String(x?.id||Date.now()+'-'+i),text:String(x?.text||'').slice(0,3000),status:['queued','done','paused'].includes(x?.status)?x.status:'queued'})).filter(x=>x.text):current.promptQueue,updatedAt:new Date().toISOString()};if(clean.status==='approved'&&!clean.approvedAt)clean.approvedAt=new Date().toISOString();await fsp.writeFile(planFile(gameDir),JSON.stringify(clean,null,2),'utf8');return clean}

export async function runHookAudit({gameDir,metadata={}}){const text=await textCorpus(gameDir),lower=text.toLowerCase();const signals={directStart:/gameplaystart|startgame|start\s*\(|pointerdown|keydown|touchstart/.test(lower),visualOnboarding:/tutorial|hint|arrow|gesture|swipe|tap|drag/.test(lower),earlyReward:/reward|coin|collect|complete|success|score/.test(lower),fastReplay:/retry|replay|play again|restart|next run|next level/.test(lower),progression:/upgrade|unlock|level|best|highscore|mission|progress/.test(lower),minimalSplash:!(/splash/.test(lower)&&/loading/.test(lower)),gameEvents:/poki.*measure|gutpopperevents|first-action|second-run/.test(lower),touch:/pointer|touch|joystick|swipe|drag/.test(lower)};const score=clamp((signals.directStart?18:0)+(signals.visualOnboarding?12:0)+(signals.earlyReward?15:0)+(signals.fastReplay?15:0)+(signals.progression?12:0)+(signals.minimalSplash?8:0)+(signals.gameEvents?10:0)+(signals.touch?10:0));const checkpoints=[{at:'0–5s',pass:signals.directStart,goal:'Player can act or understand the actionable object immediately.'},{at:'5–15s',pass:signals.visualOnboarding||signals.touch,goal:'Controls/goal are demonstrated visually with minimal reading.'},{at:'15–30s',pass:signals.earlyReward,goal:'First satisfying response/reward/impact is visible.'},{at:'30–60s',pass:signals.fastReplay||signals.progression,goal:'Player can see why another attempt/upgrade/goal matters.'}];const fixes=[];if(!signals.directStart)fixes.push('Remove menu friction or make the primary start action immediate and obvious.');if(!signals.visualOnboarding)fixes.push('Add one visual gesture/arrow/demo instead of explanatory text.');if(!signals.earlyReward)fixes.push('Move a satisfying response, collection, completion, transformation, or score beat earlier.');if(!signals.fastReplay)fixes.push('Make replay/next-run one tap and visible immediately after a terminal state.');if(!signals.progression)fixes.push('Expose a concrete mastery/upgrade/unlock/score goal before the first minute ends.');return{version:STUDIO_TOOLS_VERSION,game:metadata.id||path.basename(gameDir),score,signals,checkpoints,fixes,method:'Fast source-aware hook audit. It is an internal heuristic; real Poki recordings remain authoritative.'}}

export function thumbnailDirections({metadata={},plan={}}){const title=metadata.title||metadata.id||'Game',concept=metadata.concept||'',theme=(plan.artDirection||concept).slice(0,180);return[{id:'hero-action',label:'Hero Action',brief:'One oversized hero/mascot doing the core action at peak readability. No UI. One threat/reward. Strong foreground/background separation.'},{id:'before-after',label:'Before → After',brief:'Show the satisfying transformation or outcome in one frame: dirty→clean, broken→fixed, small→upgraded, empty→full, etc.'},{id:'cute-chaos',label:'Cute + Chaos',brief:'Put the most expressive/cute/weird character in the center with one exaggerated problem and bright reward objects around it.'},{id:'mystery-goal',label:'Obvious Mystery',brief:'Show a visually strange objective players instantly want to resolve; keep the mechanic readable without explanatory text.'}].map(x=>({...x,title,theme}))}

export async function runOptimizationAudit({gameDir}){const files=await walk(gameDir),rows=[],hashes=new Map();let total=0;for(const rel of files){let stat;try{stat=await fsp.stat(path.join(gameDir,rel))}catch{continue}total+=stat.size;const ext=path.extname(rel).toLowerCase();const row={path:rel.replaceAll('\\','/'),bytes:stat.size,ext};rows.push(row);if(stat.size<=8*1024*1024){try{const h=createHash('sha1').update(await fsp.readFile(path.join(gameDir,rel))).digest('hex');if(!hashes.has(h))hashes.set(h,[]);hashes.get(h).push(row.path)}catch{}}}const corpus=await textCorpus(gameDir);const duplicates=[...hashes.values()].filter(x=>x.length>1);const large=rows.filter(x=>x.bytes>750*1024).sort((a,b)=>b.bytes-a.bytes).slice(0,20);const transparent=(corpus.match(/transparent\s*:\s*true|opacity\s*[:=]/gi)||[]).length,lights=(corpus.match(/pointlight|spotlight/gi)||[]).length,post=(corpus.match(/effectcomposer|ssaopass|bloompass|unrealbloom|depthoffield|motionblur/gi)||[]).length,instanced=/instancedmesh/i.test(corpus);const score=clamp(100-Math.min(30,large.length*4)-Math.min(18,duplicates.length*4)-Math.min(12,Math.max(0,lights-3)*2)-Math.min(18,post*6)-Math.min(8,Math.max(0,transparent-15)/3)+(instanced?5:0));const notes=[];if(large.length)notes.push('Review large initial assets and convert/compress/defer anything not needed for first interaction.');if(duplicates.length)notes.push('Deduplicate identical files/material assets.');if(lights>3)notes.push('Reduce realtime point/spot lights; prefer one key light plus ambient/faked emissive accents.');if(post)notes.push('Expensive post-processing detected; mobile Poki default should remain zero fullscreen post passes.');if(transparent>15)notes.push('Many transparent/opacity surfaces detected; reduce overdraw on mobile.');if(!instanced&&/three/i.test(corpus))notes.push('Consider InstancedMesh/shared geometry for repeated scenery or collectibles.');return{version:STUDIO_TOOLS_VERSION,score,totalBytes:total,fileCount:rows.length,largeFiles:large,duplicateGroups:duplicates,signals:{transparentReferences:transparent,realtimeLightReferences:lights,postProcessReferences:post,usesInstancing:instanced},notes}}

export function detectGodot(){const commands=process.platform==='win32'?[['where.exe',['godot4']],['where.exe',['godot']]]:[['which',['godot4']],['which',['godot']]];for(const [cmd,args] of commands){const found=spawnSync(cmd,args,{encoding:'utf8',windowsHide:true});if(found.status===0&&found.stdout.trim()){const executable=found.stdout.trim().split(/\r?\n/)[0],v=spawnSync(executable,['--version'],{encoding:'utf8',windowsHide:true});return{installed:true,executable,version:(v.stdout||v.stderr||'').trim()}}}return{installed:false,executable:null,version:null}}

export function advancedAssetStatus(){return{referenceRouting:true,billboard:true,vectorExtrusion:true,proceduralModel:true,glbImport:false,imageTo3dProvider:false,note:'True image→multi-view 3D/GLB generation needs an external or local model provider. Factory does not fake this capability.'}}

export function portfolioRank({games=[],jobs=[],funnels={}}){const latest=new Map();for(const job of jobs){if(!latest.has(job.game))latest.set(job.game,job)}return games.map(game=>{const job=latest.get(game.id),audit=job?.studioLoopResult?.audit||null,funnel=funnels[game.id]||null,test=funnel?.tests?.at?.(-1)||funnel?.tests?.[funnel.tests.length-1]||null;let market=0;if(test?.stage==='player-fit'){market=Math.min(100,Math.round((Number(test.averageMinutes||0)/5)*55+(Number(test.over3MinutesPercent||0)/35)*45))}else if(test?.stage==='web-fit'){market=Math.min(100,Math.round((Number(test.averageMinutes||0)/6)*45+(Number(test.conversionToPlayPercent||0)/70)*55))}else if(test?.stage==='recordings')market=Math.min(60,Number(test.recordingsWatched||0)*6);const internal=audit?Math.round((Number(audit.overallScore||0)+Number(audit.visualScore||0)+Number(audit.playtestScore||0))/3):job?.qa?.passed?55:25;const score=Math.round(market*.65+internal*.35);const status=market>=78?'PROMOTE':market>=55?'ITERATE':test&&market<35?'PARK / REMAKE':internal>=75?'READY TO TEST':'BUILD / POLISH';return{id:game.id,title:game.title,score,status,marketScore:market,internalScore:internal,latestTest:test||null,doctor:audit?{overall:audit.overallScore,visual:audit.visualScore,playtest:audit.playtestScore,performance:audit.performanceScore}:null}}).sort((a,b)=>b.score-a.score)}
